### ISSUE TITLE
Select model definitions tool (Pydantic, dataclass, maybe other)

### ISSUE THREAD

**Issue by RaczeQ** [srai-lab/srai#21]

**Comment by RaczeQ** [comment]
Chosen pydantic for now

**Comment by Calychas** [comment]
Stumbled upon [this article](https://towardsdatascience.com/battle-of-the-data-containers-which-python-typed-structure-is-the-best-6d28fde824e) that shows, that pydantic is not that fast and memory efficient comparing e.g. to dataclass. We can leave pydantic for now, but I'm still unsure of the advantages of pydantic for our use case comparing to other solutions. BTW I've never used pydantic so it may be the case that its api is cleaner or something

**Comment by RaczeQ** [comment]
We will remove pydantic for now and stick to the dataclass solution.
