### ISSUE TITLE
Add logging mechanism

### ISSUE THREAD

**Issue by RaczeQ** [srai-lab/srai#22]
Setup logging and rich library

**Comment by Calychas** [comment]
I'm thinking that logging configuration and rich should be used in a "consumer" project that uses our srai library. [Reason](https://docs.python.org/3/howto/logging.html#:~:text=than%20just%20%E2%80%98foo%E2%80%99.-,Note,-It%20is%20strongly), and you need to [add a handler to enable rich logging](https://rich.readthedocs.io/en/stable/logging.html). I'm for leaving this for later.
