### ISSUE TITLE
Add package version information file with automatic update

### ISSUE THREAD

**Issue by RaczeQ** [srai-lab/srai#305]
A baked version number in a dedicated file can improve usage for end users.
Example file: https://github.com/gboeing/osmnx/blob/main/osmnx/_version.py

**Comment by Calychas** [comment]
It is recommended by pep8, but adding it would require changing version in 2 places on bump. See if it is possible to automatically generate it e.g. from pyproject.toml

**Comment by Calychas** [comment]
See https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ for more
