### ISSUE TITLE
Add base and dev dependencies to pyproject.toml

### ISSUE THREAD

**Issue by RaczeQ** [srai-lab/srai#8]
Core libraries:
- Geospatial
  - GeoPandas
  - Pandas (explicit versioning)
  - Numpy (explicit versioning)
  - Shapely (explicit versioning)
  - H3 (4.0 is in alpha, 3.7.4 is current version)
- Utility
  - tqdm (alive-bar as alternative)

Test useful libraries for parallelization:

- numba?
- dask?
- celery XD
- ray
- swifter
- pandarallel

Optional dependencies:

- Visualization
  - seaborn (optional)
  - leaflet
- ML / AI - training
  - Scikit (?)
  - PyTorch
  - PyTorchGeo
- OpenStreetMap (test what will be useful)
  - OSMPythonTools
  - osmnx

Development:
- black
- isort
- flake8

Docs (select one):
- sphinx
- quattro
- MkDocs (fastapi uses this one)
- diagrams library (generating diagrams as a code)

Add useful libraries:

- [PyFunctional](https://github.com/EntilZha/PyFunctional)
- [more-itertools](https://github.com/more-itertools/more-itertools) (add only when needed)

**Comment by RaczeQ** [comment]
Progress bar: I'd suggest using [alive-progress](https://github.com/rsalmei/alive-progress) since it's more responsive and prettier than tqdm imo.

**Comment by Calychas** [comment]
> Progress bar: I'd suggest using [alive-progress](https://github.com/rsalmei/alive-progress) since it's more responsive and prettier than tqdm IMO. And it works with prints and logger out of the box.

Looks really good and I think we can try it. Just wondering how it cooperates with e.g. pandas, where with tqdm you can do just `df.progress_apply(...)` and it shows the progress bar right away.

My opinion is to try alive-progress (add as a dev dependency??) and if it doesn't meet our standards then we'll go back to tqdm
